CREATE DATABASE CARS;
USE cars ;
__ READ DATA __
SELECT * FROM prerana;
-- TOTAL CARS TO GET A COUNT OF TOTAL RECORDS --
SELECT COUNT(*)
FROM prerana; #7927 
--THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVALIABLE IN 2023 --
SELECT COUNT(*)
FROM prerana #6
WHERE YEAR = 2023;
-- HOW MANY CARS ARE AVALIABLE FOR 2020 ,2021, 2022?
SELECT COUNT(*)
FROM prerana #74
WHERE YEAR =2020;

SELECT COUNT(*)
FROM prerana #7
WHERE YEAR = 2021;

SELECT COUNT(*)
FROM prerana #7
WHERE YEAR =2022;

SELECT COUNT(*)
FROM prerana #88
WHERE YEAR IN (2020 , 2021 ,2022);
-- CLIENT ASKED ME TO PRINT THE TOTAL OF ALL CARS BY YEAR I DONT SEE THE DETAILS --
SELECT COUNT(*) 
FROM prerana #6,7,7,74,583
GROUP BY YEAR;

-- CLIENT ASKED HOW MANY DIESEL CARS WILL BE THERE IN 2020?--
SELECT COUNT(*)
FROM prerana #20
WHERE FUEL = "DIESEL"  AND YEAR =2020
-- CLIENT ASKED HOW MANY PETROL CARS WILL BE THERE IN 2020?--
SELECT COUNT(*)
FROM prerana #51
WHERE FUEL ="PETROL" AND YEAR= 2020 ;
-- THE MANAGER TOLD THE EMPLOYEE TO GIVE A PRINT OF ALL FUEL CARS (PETROL,DIESEL AND CNG ) COME ALL BY YEAR?
SELECT YEAR ,COUNT(*)
FROM prerana # 4,5,5,51,352
WHERE FUEL = "PETROL"
GROUP BY YEAR ;
--MANAGER SAID THEIR WERE MORE THAN 100 CARS IN A GIVEN YEAR ... WHCH YEAR HAD MORE THAN 100 CAR ?---
SELECT YEAR , COUNT(*)
FROM prerana #583,806 ,1010, 856 ,775
GROUP BY YEAR
HAVING COUNT(*) > 100

-- THE MANAGER SAID TO EMPLOYEE TO GET ALL CARS COUNT DETAIL BETWEEN 2015 AND 2016 WE NEED A COMPLETE LIST?--
SELECT  COUNT(*)
FROM prerana #1631
WHERE YEAR BETWEEN 2015 AND 2016

--THE MANAGER SAID TO EMPLOYEE TO GET ALL CARS COUNT DETAIL BETWEEN 2015 AND 2023 WE NEED A COMPLETE LIST?--
SELECT *
FROM prerana
WHERE YEAR BETWEEN 2015 AND 2023
